import Link from 'next/link';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { ArrowRight, Zap, Brain, Trophy, Users, BookOpen, Shield, Star, Check, Sparkles, GraduationCap, Target, Rocket } from 'lucide-react';

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-black">
      {/* Navbar */}
      <nav className="fixed top-0 z-50 w-full glass-strong">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary shadow-glow">
              <Zap className="h-5 w-5 text-white" />
            </div>
            <span className="text-xl font-bold text-white">GOALIFY</span>
          </Link>
          <div className="hidden items-center gap-8 md:flex">
            <Link href="#features" className="text-sm text-muted hover:text-white transition-colors">Features</Link>
            <Link href="#training" className="text-sm text-muted hover:text-white transition-colors">Training</Link>
            <Link href="#pricing" className="text-sm text-muted hover:text-white transition-colors">Pricing</Link>
            <Link href="#community" className="text-sm text-muted hover:text-white transition-colors">Community</Link>
          </div>
          <div className="flex items-center gap-3">
            <Link href="/login"><Button variant="ghost" size="sm">Sign In</Button></Link>
            <Link href="/register"><Button size="sm">Start Training</Button></Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative flex min-h-screen items-center justify-center overflow-hidden bg-grid pt-16">
        <div className="absolute inset-0 bg-gradient-to-b from-primary/5 via-transparent to-transparent" />
        <div className="absolute top-1/4 left-1/4 h-96 w-96 rounded-full bg-primary/10 blur-[120px]" />
        <div className="absolute bottom-1/4 right-1/4 h-96 w-96 rounded-full bg-glow/5 blur-[120px]" />
        <div className="relative z-10 mx-auto max-w-5xl px-6 text-center">
          <Badge variant="primary" className="mb-6"><Sparkles className="mr-1 h-3 w-3" /> AI-Powered Learning Platform</Badge>
          <h1 className="mb-6 text-5xl font-bold leading-tight tracking-tight md:text-7xl">
            Train Smarter.<br />
            <span className="text-gradient">Level Up Faster.</span>
          </h1>
          <p className="mx-auto mb-10 max-w-2xl text-lg text-muted md:text-xl">
            AI-generated training programs, personalized coaching, and a community of ambitious learners. 
            Your personal development journey starts here.
          </p>
          <div className="flex flex-col items-center justify-center gap-4 sm:flex-row">
            <Link href="/register"><Button size="lg">Start Free Training <ArrowRight className="ml-2 h-4 w-4" /></Button></Link>
            <Link href="#features"><Button variant="outline" size="lg">Explore Features</Button></Link>
          </div>
          <div className="mt-16 flex items-center justify-center gap-8 text-sm text-muted">
            <div className="flex items-center gap-2"><Users className="h-4 w-4 text-primary" /> 15K+ Learners</div>
            <div className="flex items-center gap-2"><BookOpen className="h-4 w-4 text-primary" /> 500+ Programs</div>
            <div className="flex items-center gap-2"><Trophy className="h-4 w-4 text-primary" /> 98% Completion</div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="relative py-24">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mb-16 text-center">
            <Badge variant="primary" className="mb-4">Features</Badge>
            <h2 className="mb-4 text-3xl font-bold md:text-5xl">Everything You Need to <span className="text-gradient-blue">Excel</span></h2>
            <p className="mx-auto max-w-2xl text-muted">AI-powered tools designed to accelerate your personal and professional growth.</p>
          </div>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {[
              { icon: Brain, title: 'AI Training Programs', desc: 'Personalized courses generated by AI based on your goals, skill level, and learning pace.', color: 'text-primary' },
              { icon: GraduationCap, title: 'AI Mentor', desc: 'Your personal AI mentor that guides you through your learning journey with expert insights.', color: 'text-glow' },
              { icon: Target, title: 'AI Learning Paths', desc: 'Structured roadmaps that take you from beginner to expert in any skill.', color: 'text-purple-400' },
              { icon: Trophy, title: 'Certificates', desc: 'Earn verified certificates upon completion to showcase your achievements.', color: 'text-warning' },
              { icon: Users, title: 'Community Rankings', desc: 'Compete with learners worldwide. Climb the leaderboard and earn XP.', color: 'text-success' },
              { icon: Shield, title: 'Student Program', desc: 'Students get Premium free. Verify your student status and unlock all features.', color: 'text-primary' },
            ].map((f, i) => (
              <Card key={i} variant="glass" hover padding="lg" className="group">
                <div className={`mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-white/5 ${f.color} group-hover:shadow-glow-sm transition-all`}>
                  <f.icon className="h-6 w-6" />
                </div>
                <h3 className="mb-2 text-lg font-semibold text-white">{f.title}</h3>
                <p className="text-sm text-muted leading-relaxed">{f.desc}</p>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Training Preview */}
      <section id="training" className="relative py-24 bg-gradient-to-b from-transparent via-primary/[0.02] to-transparent">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mb-16 text-center">
            <Badge variant="success" className="mb-4">AI Training</Badge>
            <h2 className="mb-4 text-3xl font-bold md:text-5xl">Learn Any Skill with <span className="text-gradient-blue">AI Precision</span></h2>
            <p className="mx-auto max-w-2xl text-muted">Our AI analyzes your goals and creates a custom training program just for you.</p>
          </div>
          <div className="grid gap-8 lg:grid-cols-3">
            {[
              { title: 'Leadership & Management', category: 'Business', difficulty: 'Intermediate', lessons: 24, hours: 12, rating: 4.9 },
              { title: 'Full-Stack Development', category: 'Technology', difficulty: 'Advanced', lessons: 48, hours: 30, rating: 4.8 },
              { title: 'Public Speaking Mastery', category: 'Communication', difficulty: 'Beginner', lessons: 16, hours: 8, rating: 4.9 },
            ].map((p, i) => (
              <Card key={i} variant="glass" hover padding="none" className="overflow-hidden">
                <div className="h-40 bg-gradient-to-br from-primary/20 to-glow/10 flex items-center justify-center">
                  <BookOpen className="h-12 w-12 text-primary/50" />
                </div>
                <div className="p-5">
                  <Badge variant="primary" className="mb-2">{p.category}</Badge>
                  <h3 className="mb-1 text-lg font-semibold text-white">{p.title}</h3>
                  <div className="mb-3 flex items-center gap-3 text-xs text-muted">
                    <span>{p.lessons} lessons</span>
                    <span>{p.hours}h</span>
                    <span className="flex items-center gap-1"><Star className="h-3 w-3 text-warning fill-warning" />{p.rating}</span>
                  </div>
                  <Badge variant={p.difficulty === 'Beginner' ? 'success' : p.difficulty === 'Intermediate' ? 'warning' : 'danger'}>{p.difficulty}</Badge>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="relative py-24">
        <div className="mx-auto max-w-5xl px-6">
          <div className="mb-16 text-center">
            <Badge variant="warning" className="mb-4">Pricing</Badge>
            <h2 className="mb-4 text-3xl font-bold md:text-5xl">Invest in <span className="text-gradient-blue">Yourself</span></h2>
            <p className="mx-auto max-w-2xl text-muted">Students get Premium free. Start free, upgrade when you&apos;re ready.</p>
          </div>
          <div className="grid gap-8 md:grid-cols-3">
            {/* Free */}
            <Card variant="glass" padding="lg">
              <h3 className="text-lg font-semibold text-white">Free</h3>
              <div className="my-4"><span className="text-4xl font-bold text-white">€0</span><span className="text-muted">/mo</span></div>
              <p className="mb-6 text-sm text-muted">Perfect for getting started</p>
              <div className="mb-6 space-y-3">
                {['3 training programs', 'Basic AI coach', 'Community access', 'Progress tracking', 'Standard certificates'].map((f, i) => (
                  <div key={i} className="flex items-center gap-2 text-sm text-muted"><Check className="h-4 w-4 text-success" />{f}</div>
                ))}
              </div>
              <Link href="/register"><Button variant="outline" className="w-full">Get Started</Button></Link>
            </Card>
            {/* Pro */}
            <Card variant="glass" hover padding="lg" className="border-primary/30 relative">
              <div className="absolute -top-3 left-1/2 -translate-x-1/2"><Badge variant="primary">Most Popular</Badge></div>
              <h3 className="text-lg font-semibold text-white">Pro</h3>
              <div className="my-4"><span className="text-4xl font-bold text-white">€3</span><span className="text-muted">/mo</span></div>
              <p className="mb-6 text-sm text-muted">For serious learners</p>
              <div className="mb-6 space-y-3">
                {['Unlimited programs', 'Advanced analytics', 'Priority support', 'All free features', 'Pro certificates'].map((f, i) => (
                  <div key={i} className="flex items-center gap-2 text-sm text-muted"><Check className="h-4 w-4 text-primary" />{f}</div>
                ))}
              </div>
              <Link href="/register"><Button className="w-full">Upgrade to Pro</Button></Link>
            </Card>
            {/* Premium */}
            <Card variant="glass" hover padding="lg" className="relative overflow-hidden">
              <div className="absolute inset-0 bg-gradient-to-b from-primary/5 to-transparent" />
              <div className="relative">
                <h3 className="text-lg font-semibold text-white">Premium</h3>
                <div className="my-4"><span className="text-4xl font-bold text-white">€5</span><span className="text-muted">/mo</span></div>
                <p className="mb-6 text-sm text-muted">For the ambitious</p>
                <div className="mb-6 space-y-3">
                  {['AI Personal Trainer', 'AI Mentor', 'AI-generated roadmaps', 'Weekly AI reports', 'Premium certificates', 'All Pro features'].map((f, i) => (
                    <div key={i} className="flex items-center gap-2 text-sm text-muted"><Check className="h-4 w-4 text-glow" />{f}</div>
                  ))}
                </div>
                <Link href="/register"><Button variant="outline" className="w-full border-primary/30 text-primary hover:bg-primary/10">Go Premium</Button></Link>
              </div>
            </Card>
          </div>
          {/* Student banner */}
          <Card variant="glass" padding="lg" className="mt-8 border-primary/20">
            <div className="flex flex-col items-center justify-between gap-4 md:flex-row">
              <div className="flex items-center gap-4">
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10">
                  <GraduationCap className="h-6 w-6 text-primary" />
                </div>
                <div>
                  <h3 className="font-semibold text-white">Student? Get Premium Free 🎓</h3>
                  <p className="text-sm text-muted">Verify your student status and unlock all Premium features at no cost.</p>
                </div>
              </div>
              <Link href="/register"><Button variant="outline" size="sm">Verify Student Status</Button></Link>
            </div>
          </Card>
        </div>
      </section>

      {/* Community */}
      <section id="community" className="relative py-24 bg-gradient-to-b from-transparent via-primary/[0.02] to-transparent">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mb-16 text-center">
            <Badge variant="purple" className="mb-4">Community</Badge>
            <h2 className="mb-4 text-3xl font-bold md:text-5xl">Join <span className="text-gradient-blue">15,000+</span> Learners</h2>
            <p className="mx-auto max-w-2xl text-muted">Compete, collaborate, and grow with a community of ambitious people.</p>
          </div>
          <div className="grid gap-6 md:grid-cols-3">
            {[
              { name: 'Sarah K.', role: 'Software Engineer', xp: 4250, level: 8, avatar: 'SK', programs: 12 },
              { name: 'Marcus J.', role: 'Product Manager', xp: 3800, level: 7, avatar: 'MJ', programs: 10 },
              { name: 'Elena R.', role: 'UX Designer', xp: 3200, level: 6, avatar: 'ER', programs: 8 },
            ].map((u, i) => (
              <Card key={i} variant="glass" hover padding="lg" className="text-center">
                <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-gradient-to-br from-primary to-glow text-xl font-bold text-white shadow-glow">
                  {u.avatar}
                </div>
                <h3 className="font-semibold text-white">{u.name}</h3>
                <p className="text-sm text-muted">{u.role}</p>
                <div className="mt-4 flex items-center justify-center gap-4 text-sm">
                  <div><span className="font-bold text-primary">{u.xp.toLocaleString()}</span> <span className="text-muted">XP</span></div>
                  <div><span className="font-bold text-glow">Lvl {u.level}</span></div>
                  <div><span className="font-bold text-warning">{u.programs}</span> <span className="text-muted">programs</span></div>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="relative py-24">
        <div className="absolute inset-0 bg-gradient-to-t from-primary/10 via-transparent to-transparent" />
        <div className="relative z-10 mx-auto max-w-3xl px-6 text-center">
          <Rocket className="mx-auto mb-6 h-12 w-12 text-primary" />
          <h2 className="mb-4 text-3xl font-bold md:text-5xl">Ready to <span className="text-gradient">Level Up?</span></h2>
          <p className="mb-8 text-lg text-muted">Join thousands of learners already training with AI. Start free today.</p>
          <Link href="/register"><Button size="lg">Start Training Now <ArrowRight className="ml-2 h-4 w-4" /></Button></Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/5 py-12">
        <div className="mx-auto max-w-7xl px-6">
          <div className="flex flex-col items-center justify-between gap-6 md:flex-row">
            <div className="flex items-center gap-2">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/20">
                <Zap className="h-4 w-4 text-primary" />
              </div>
              <span className="font-bold text-white">GOALIFY</span>
            </div>
            <div className="flex gap-6 text-sm text-muted">
              <Link href="#" className="hover:text-white transition-colors">Terms</Link>
              <Link href="#" className="hover:text-white transition-colors">Privacy</Link>
              <Link href="#" className="hover:text-white transition-colors">Contact</Link>
              <Link href="#" className="hover:text-white transition-colors">Student Program</Link>
            </div>
            <p className="text-sm text-muted">© 2026 Goalify. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
