export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as Problem } from "./Problem";
export { default as Features } from "./Features";
export { default as AIShowcase } from "./AIShowcase";
export { default as Pricing } from "./Pricing";
export { default as Testimonials } from "./Testimonials";
export { default as FAQ } from "./FAQ";
export { default as Footer } from "./Footer";
